server:
  port: 8080
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 2000
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true


logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.web: DEBUG
    org.hibernate.type: trace
